### ISSUE TITLE
Crash upon first use

### ISSUE THREAD

**Issue by PlayBoxTech** [Doggettx/stable-diffusion#3]
Using a NVIDIA GeForce RTX 3060 Ti with 8192 MB I get the following error: 
Sampling:   0%|                                                                                                                                                                                                          | 0/2 [00:00<?, ?it/sData shape for PLMS sampling is (3, 4, 64, 64)                                                                                                                                                                            | 0/1 [00:00<?, ?it/s]
Running PLMS Sampling with 50 timesteps
PLMS Sampler:   0%|                                                                                                                                                                                                     | 0/50 [00:02<?, ?it/s]
data:   0%|                                                                                                                                                                                                              | 0/1 [00:14<?, ?it/s]
Sampling:   0%|                                                                                                                                                                                                          | 0/2 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 295, in main
    samples_ddim, _ = sampler.sample(S=opt.ddim_steps,
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/models/diffusion/plms.py", line 97, in sample
    samples, intermediates = self.plms_sampling(conditioning, size,
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/models/diffusion/plms.py", line 152, in plms_sampling
    outs = self.p_sample_plms(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/models/diffusion/plms.py", line 218, in p_sample_plms
    e_t = get_model_output(x, t)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/models/diffusion/plms.py", line 185, in get_model_output
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/diffusionmodules/openaimodel.py", line 732, in forward
    h = module(h, emb, context)
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/diffusionmodules/openaimodel.py", line 85, in forward
    x = layer(x, context)
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/attention.py", line 276, in forward
    x = block(x, context=context)
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/attention.py", line 227, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/diffusionmodules/util.py", line 127, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/attention.py", line 230, in _forward
    x = self.attn1(self.norm1(x)) + x
  File "/home/chris/anaconda3/envs/dogg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/stable2/dogg/stable-diffusion/ldm/modules/attention.py", line 200, in forward
    s2 = s1.softmax(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 7.79 GiB total capacity; 4.52 GiB already allocated; 749.19 MiB free; 4.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Doggettx** [comment]
I just checked in a new update, should fix this issue...

**Comment by PlayBoxTech** [comment]
Yes, issue is now fixed.
